org: serhiiholovanenko
app: my-first-app

service: app

provider:
    name: aws
    region: eu-central-1
    runtime: provided

plugins:
  - ./vendor/bref/bref
  - serverless-step-functions
functions:
    function:
        handler: index.php
        description: ''
        layers:
            - ${bref:layer.php-73}

# Exclude files from deployment
package:
    exclude:
        - 'tests/**'
